// weatherMapping.js
export const backgroundImages = {
  '01d': 'clear-day',
  '01n': 'clear-night',
  '02d': 'few-clouds-day',
  '02n': 'few-clouds-night',
  '03d': 'cloudy-day',
  '03n': 'cloudy-night',
  '04d': 'cloudy-day',
  '04n': 'cloudy-night',
  '09d': 'rain-day',
  '09n': 'rain-night',
  '10d': 'rain-day',
  '10n': 'rain-night',
  '11d': 'storm-day',
  '11n': 'storm-night',
  '13d': 'snow-day',
  '13n': 'snow-night',
  '50d': 'cloudy-day',
  '50n': 'cloudy-night',
};

export const weatherSymbols = {
  '01d': 'clear-day',
  '01n': 'clear-night',
  '02d': 'few-clouds-day',
  '02n': 'few-clouds-night',
  '03d': 'cloudy-day',
  '03n': 'cloudy-night',
  '04d': 'cloudy-day',
  '04n': 'cloudy-night',
  '09d': 'rain-day',
  '09n': 'rain-night',
  '10d': 'rain-day',
  '10n': 'rain-night',
  '11d': 'storm-day',
  '11n': 'storm-night',
  '13d': 'snow-day',
  '13n': 'snow-night',
  '50d': 'cloudy-day',
  '50n': 'cloudy-night',
  default: 'default',
};
